<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use App\Models\User;
use App\Models\Unit;
use App\Models\Position;
use App\Models\Rank;

class EmployeesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Get reference data
        $units = Unit::all()->keyBy('code');
        $positions = Position::all()->keyBy('name');
        $ranks = Rank::all()->keyBy('code');

        $employees = [
            // BPKAD - Badan Pengelola Keuangan dan Aset Daerah
            [
                'name' => 'Ahmad Rizki',
                'email' => 'ahmad.rizki@perjadin.test',
                'password' => Hash::make('password'),
                'nip' => '198603012010011001',
                'nik' => '1401010101860001',
                'gelar_depan' => '',
                'gelar_belakang' => 'S.E., M.M.',
                'phone' => '081234567816',
                'whatsapp' => '081234567816',
                'address' => 'Jl. BPKAD No. 2, Bengkalis',
                'unit_id' => $units['BPKAD']->id ?? null,
                'position_id' => $positions['Kepala Seksi']->id ?? null,
                'position_desc' => 'Kepala Seksi Perbendaharaan',
                'rank_id' => $ranks['III/c']->id ?? null,
                'npwp' => '12.345.678.9-123.482',
                'bank_name' => 'Bank Riau Kepri',
                'bank_account_no' => '1234567816',
                'bank_account_name' => 'AHMAD RIZKI',
                'birth_date' => '1986-03-01',
                'gender' => 'L',
                'is_signer' => true,
            ],
            [
                'name' => 'Siti Nurhaliza',
                'email' => 'siti.nurhaliza@perjadin.test',
                'password' => Hash::make('password'),
                'nip' => '198704012010012001',
                'nik' => '1401010101870002',
                'gelar_depan' => '',
                'gelar_belakang' => 'S.E., M.M.',
                'phone' => '081234567817',
                'whatsapp' => '081234567817',
                'address' => 'Jl. BPKAD No. 3, Bengkalis',
                'unit_id' => $units['BPKAD']->id ?? null,
                'position_id' => $positions['Kepala Seksi']->id ?? null,
                'position_desc' => 'Kepala Seksi Anggaran',
                'rank_id' => $ranks['III/c']->id ?? null,
                'npwp' => '12.345.678.9-123.483',
                'bank_name' => 'Bank Riau Kepri',
                'bank_account_no' => '1234567817',
                'bank_account_name' => 'SITI NURHALIZA',
                'birth_date' => '1987-04-01',
                'gender' => 'P',
                'is_signer' => true,
            ],
            [
                'name' => 'Budi Santoso',
                'email' => 'budi.santoso@perjadin.test',
                'password' => Hash::make('password'),
                'nip' => '198805012010011001',
                'nik' => '1401010101880002',
                'gelar_depan' => '',
                'gelar_belakang' => 'S.E.',
                'phone' => '081234567818',
                'whatsapp' => '081234567818',
                'address' => 'Jl. BPKAD No. 4, Bengkalis',
                'unit_id' => $units['BPKAD']->id ?? null,
                'position_id' => $positions['Staff']->id ?? null,
                'position_desc' => 'Staff Perbendaharaan',
                'rank_id' => $ranks['III/b']->id ?? null,
                'npwp' => '12.345.678.9-123.484',
                'bank_name' => 'Bank Riau Kepri',
                'bank_account_no' => '1234567818',
                'bank_account_name' => 'BUDI SANTOSO',
                'birth_date' => '1988-05-01',
                'gender' => 'L',
                'is_signer' => false,
            ],

            // BPKAD-KEU - Bidang Perbendaharaan
            [
                'name' => 'Maya Sari',
                'email' => 'maya.sari@perjadin.test',
                'password' => Hash::make('password'),
                'nip' => '198906012010012001',
                'nik' => '1401010101890002',
                'gelar_depan' => '',
                'gelar_belakang' => 'S.E., M.M.',
                'phone' => '081234567819',
                'whatsapp' => '081234567819',
                'address' => 'Jl. BPKAD No. 5, Bengkalis',
                'unit_id' => $units['BPKAD-KEU']->id ?? null,
                'position_id' => $positions['Kepala Seksi']->id ?? null,
                'position_desc' => 'Kepala Seksi Kas Daerah',
                'rank_id' => $ranks['III/c']->id ?? null,
                'npwp' => '12.345.678.9-123.485',
                'bank_name' => 'Bank Riau Kepri',
                'bank_account_no' => '1234567819',
                'bank_account_name' => 'MAYA SARI',
                'birth_date' => '1989-06-01',
                'gender' => 'P',
                'is_signer' => true,
            ],
            [
                'name' => 'Hendra Wijaya',
                'email' => 'hendra.wijaya@perjadin.test',
                'password' => Hash::make('password'),
                'nip' => '199007012010011001',
                'nik' => '1401010101900003',
                'gelar_depan' => '',
                'gelar_belakang' => 'S.E.',
                'phone' => '081234567820',
                'whatsapp' => '081234567820',
                'address' => 'Jl. BPKAD No. 6, Bengkalis',
                'unit_id' => $units['BPKAD-KEU']->id ?? null,
                'position_id' => $positions['Staff']->id ?? null,
                'position_desc' => 'Staff Kas Daerah',
                'rank_id' => $ranks['III/b']->id ?? null,
                'npwp' => '12.345.678.9-123.486',
                'bank_name' => 'Bank Riau Kepri',
                'bank_account_no' => '1234567820',
                'bank_account_name' => 'HENDRA WIJAYA',
                'birth_date' => '1990-07-01',
                'gender' => 'L',
                'is_signer' => false,
            ],

            // BPKAD-ANG - Bidang Anggaran
            [
                'name' => 'Bambang Setiawan',
                'email' => 'bambang.setiawan@perjadin.test',
                'password' => Hash::make('password'),
                'nip' => '199209012010011001',
                'nik' => '1401010101920002',
                'gelar_depan' => '',
                'gelar_belakang' => 'S.E., M.M.',
                'phone' => '081234567822',
                'whatsapp' => '081234567822',
                'address' => 'Jl. BPKAD No. 7, Bengkalis',
                'unit_id' => $units['BPKAD-ANG']->id ?? null,
                'position_id' => $positions['Kepala Seksi']->id ?? null,
                'position_desc' => 'Kepala Seksi Penyusunan Anggaran',
                'rank_id' => $ranks['III/c']->id ?? null,
                'npwp' => '12.345.678.9-123.488',
                'bank_name' => 'Bank Riau Kepri',
                'bank_account_no' => '1234567822',
                'bank_account_name' => 'BAMBANG SETIAWAN',
                'birth_date' => '1992-09-01',
                'gender' => 'L',
                'is_signer' => true,
            ],
            [
                'name' => 'Dian Purnama',
                'email' => 'dian.purnama@perjadin.test',
                'password' => Hash::make('password'),
                'nip' => '199310012010012001',
                'nik' => '1401010101930002',
                'gelar_depan' => '',
                'gelar_belakang' => 'S.E.',
                'phone' => '081234567823',
                'whatsapp' => '081234567823',
                'address' => 'Jl. BPKAD No. 8, Bengkalis',
                'unit_id' => $units['BPKAD-ANG']->id ?? null,
                'position_id' => $positions['Staff']->id ?? null,
                'position_desc' => 'Staff Penyusunan Anggaran',
                'rank_id' => $ranks['III/b']->id ?? null,
                'npwp' => '12.345.678.9-123.489',
                'bank_name' => 'Bank Riau Kepri',
                'bank_account_no' => '1234567823',
                'bank_account_name' => 'DIAN PURNAMA',
                'birth_date' => '1993-10-01',
                'gender' => 'P',
                'is_signer' => false,
            ],

            // BPKAD-ASET - Bidang Aset
            [
                'name' => 'Rudi Hartono',
                'email' => 'rudi.hartono@perjadin.test',
                'password' => Hash::make('password'),
                'nip' => '199411012010011001',
                'nik' => '1401010101940002',
                'gelar_depan' => '',
                'gelar_belakang' => 'S.E., M.M.',
                'phone' => '081234567824',
                'whatsapp' => '081234567824',
                'address' => 'Jl. BPKAD No. 9, Bengkalis',
                'unit_id' => $units['BPKAD-ASET']->id ?? null,
                'position_id' => $positions['Kepala Seksi']->id ?? null,
                'position_desc' => 'Kepala Seksi Pengelolaan Aset',
                'rank_id' => $ranks['III/c']->id ?? null,
                'npwp' => '12.345.678.9-123.490',
                'bank_name' => 'Bank Riau Kepri',
                'bank_account_no' => '1234567824',
                'bank_account_name' => 'RUDI HARTONO',
                'birth_date' => '1994-11-01',
                'gender' => 'L',
                'is_signer' => true,
            ],
            [
                'name' => 'Sri Wahyuni',
                'email' => 'sri.wahyuni@perjadin.test',
                'password' => Hash::make('password'),
                'nip' => '199512012010012001',
                'nik' => '1401010101950002',
                'gelar_depan' => '',
                'gelar_belakang' => 'S.E.',
                'phone' => '081234567825',
                'whatsapp' => '081234567825',
                'address' => 'Jl. BPKAD No. 10, Bengkalis',
                'unit_id' => $units['BPKAD-ASET']->id ?? null,
                'position_id' => $positions['Staff']->id ?? null,
                'position_desc' => 'Staff Pengelolaan Aset',
                'rank_id' => $ranks['III/b']->id ?? null,
                'npwp' => '12.345.678.9-123.491',
                'bank_name' => 'Bank Riau Kepri',
                'bank_account_no' => '1234567825',
                'bank_account_name' => 'SRI WAHYUNI',
                'birth_date' => '1995-12-01',
                'gender' => 'P',
                'is_signer' => false,
            ],

            // BPKAD-AKU - Bidang Akuntansi dan Pelaporan
            [
                'name' => 'Ahmad Fauzi',
                'email' => 'ahmad.fauzi@perjadin.test',
                'password' => Hash::make('password'),
                'nip' => '199601012010011001',
                'nik' => '1401010101960002',
                'gelar_depan' => '',
                'gelar_belakang' => 'S.E., M.M.',
                'phone' => '081234567826',
                'whatsapp' => '081234567826',
                'address' => 'Jl. BPKAD No. 11, Bengkalis',
                'unit_id' => $units['BPKAD-AKU']->id ?? null,
                'position_id' => $positions['Kepala Seksi']->id ?? null,
                'position_desc' => 'Kepala Seksi Akuntansi',
                'rank_id' => $ranks['III/c']->id ?? null,
                'npwp' => '12.345.678.9-123.492',
                'bank_name' => 'Bank Riau Kepri',
                'bank_account_no' => '1234567826',
                'bank_account_name' => 'AHMAD FAUZI',
                'birth_date' => '1996-01-01',
                'gender' => 'L',
                'is_signer' => true,
            ],
            [
                'name' => 'Nina Marlina',
                'email' => 'nina.marlina@perjadin.test',
                'password' => Hash::make('password'),
                'nip' => '199702012010012001',
                'nik' => '1401010101970002',
                'gelar_depan' => '',
                'gelar_belakang' => 'S.E.',
                'phone' => '081234567827',
                'whatsapp' => '081234567827',
                'address' => 'Jl. BPKAD No. 12, Bengkalis',
                'unit_id' => $units['BPKAD-AKU']->id ?? null,
                'position_id' => $positions['Staff']->id ?? null,
                'position_desc' => 'Staff Akuntansi',
                'rank_id' => $ranks['III/b']->id ?? null,
                'npwp' => '12.345.678.9-123.493',
                'bank_name' => 'Bank Riau Kepri',
                'bank_account_no' => '1234567827',
                'bank_account_name' => 'NINA MARLINA',
                'birth_date' => '1997-02-01',
                'gender' => 'P',
                'is_signer' => false,
            ],

            // BPKAD-SEK - Sekretariat
            [
                'name' => 'Joko Widodo',
                'email' => 'joko.widodo@perjadin.test',
                'password' => Hash::make('password'),
                'nip' => '199803012010011001',
                'nik' => '1401010101980002',
                'gelar_depan' => '',
                'gelar_belakang' => 'S.E., M.M.',
                'phone' => '081234567828',
                'whatsapp' => '081234567828',
                'address' => 'Jl. BPKAD No. 13, Bengkalis',
                'unit_id' => $units['BPKAD-SEK']->id ?? null,
                'position_id' => $positions['Kepala Seksi']->id ?? null,
                'position_desc' => 'Kepala Seksi Umum dan Kepegawaian',
                'rank_id' => $ranks['III/c']->id ?? null,
                'npwp' => '12.345.678.9-123.494',
                'bank_name' => 'Bank Riau Kepri',
                'bank_account_no' => '1234567828',
                'bank_account_name' => 'JOKO WIDODO',
                'birth_date' => '1998-03-01',
                'gender' => 'L',
                'is_signer' => true,
            ],
            [
                'name' => 'Susi Pudjiastuti',
                'email' => 'susi.pudjiastuti@perjadin.test',
                'password' => Hash::make('password'),
                'nip' => '199904012010012001',
                'nik' => '1401010101990002',
                'gelar_depan' => '',
                'gelar_belakang' => 'S.E.',
                'phone' => '081234567829',
                'whatsapp' => '081234567829',
                'address' => 'Jl. BPKAD No. 14, Bengkalis',
                'unit_id' => $units['BPKAD-SEK']->id ?? null,
                'position_id' => $positions['Staff']->id ?? null,
                'position_desc' => 'Staff Umum dan Kepegawaian',
                'rank_id' => $ranks['III/b']->id ?? null,
                'npwp' => '12.345.678.9-123.495',
                'bank_name' => 'Bank Riau Kepri',
                'bank_account_no' => '1234567829',
                'bank_account_name' => 'SUSI PUDJIASTUTI',
                'birth_date' => '1999-04-01',
                'gender' => 'P',
                'is_signer' => false,
            ],

            // Tambahan untuk BPKAD
            [
                'name' => 'Dedi Kurniawan',
                'email' => 'dedi.kurniawan@perjadin.test',
                'password' => Hash::make('password'),
                'nip' => '200005012010011001',
                'nik' => '1401010102000002',
                'gelar_depan' => '',
                'gelar_belakang' => 'S.E.',
                'phone' => '081234567830',
                'whatsapp' => '081234567830',
                'address' => 'Jl. BPKAD No. 15, Bengkalis',
                'unit_id' => $units['BPKAD']->id ?? null,
                'position_id' => $positions['Staff']->id ?? null,
                'position_desc' => 'Staff Perbendaharaan',
                'rank_id' => $ranks['III/b']->id ?? null,
                'npwp' => '12.345.678.9-123.496',
                'bank_name' => 'Bank Riau Kepri',
                'bank_account_no' => '1234567830',
                'bank_account_name' => 'DEDI KURNIAWAN',
                'birth_date' => '2000-05-01',
                'gender' => 'L',
                'is_signer' => false,
            ],
            [
                'name' => 'Siti Nurbaya',
                'email' => 'siti.nurbaya@perjadin.test',
                'password' => Hash::make('password'),
                'nip' => '200106012010012001',
                'nik' => '1401010102010001',
                'gelar_depan' => '',
                'gelar_belakang' => 'S.E., M.M.',
                'phone' => '081234567831',
                'whatsapp' => '081234567831',
                'address' => 'Jl. BPKAD No. 16, Bengkalis',
                'unit_id' => $units['BPKAD']->id ?? null,
                'position_id' => $positions['Kepala Seksi']->id ?? null,
                'position_desc' => 'Kepala Seksi Aset',
                'rank_id' => $ranks['III/c']->id ?? null,
                'npwp' => '12.345.678.9-123.497',
                'bank_name' => 'Bank Riau Kepri',
                'bank_account_no' => '1234567831',
                'bank_account_name' => 'SITI NURBAYA',
                'birth_date' => '2001-06-01',
                'gender' => 'P',
                'is_signer' => true,
            ],
            [
                'name' => 'Basuki Tjahaja Purnama',
                'email' => 'basuki.purnama@perjadin.test',
                'password' => Hash::make('password'),
                'nip' => '200207012010011001',
                'nik' => '1401010102020001',
                'gelar_depan' => '',
                'gelar_belakang' => 'S.E.',
                'phone' => '081234567832',
                'whatsapp' => '081234567832',
                'address' => 'Jl. BPKAD No. 17, Bengkalis',
                'unit_id' => $units['BPKAD']->id ?? null,
                'position_id' => $positions['Staff']->id ?? null,
                'position_desc' => 'Staff Anggaran',
                'rank_id' => $ranks['III/b']->id ?? null,
                'npwp' => '12.345.678.9-123.498',
                'bank_name' => 'Bank Riau Kepri',
                'bank_account_no' => '1234567832',
                'bank_account_name' => 'BASUKI TJHAJA PURNAMA',
                'birth_date' => '2002-07-01',
                'gender' => 'L',
                'is_signer' => false,
            ],
            [
                'name' => 'Rina Marlina',
                'email' => 'rina.marlina@perjadin.test',
                'password' => Hash::make('password'),
                'nip' => '200308012010012001',
                'nik' => '1401010102030001',
                'gelar_depan' => '',
                'gelar_belakang' => 'S.E.',
                'phone' => '081234567833',
                'whatsapp' => '081234567833',
                'address' => 'Jl. BPKAD No. 18, Bengkalis',
                'unit_id' => $units['BPKAD']->id ?? null,
                'position_id' => $positions['Staff']->id ?? null,
                'position_desc' => 'Staff Akuntansi',
                'rank_id' => $ranks['III/b']->id ?? null,
                'npwp' => '12.345.678.9-123.499',
                'bank_name' => 'Bank Riau Kepri',
                'bank_account_no' => '1234567833',
                'bank_account_name' => 'RINA MARLINA',
                'birth_date' => '2003-08-01',
                'gender' => 'P',
                'is_signer' => false,
            ],
            [
                'name' => 'Arief Yahya',
                'email' => 'arief.yahya@perjadin.test',
                'password' => Hash::make('password'),
                'nip' => '200409012010011001',
                'nik' => '1401010102040001',
                'gelar_depan' => '',
                'gelar_belakang' => 'S.E., M.M.',
                'phone' => '081234567834',
                'whatsapp' => '081234567834',
                'address' => 'Jl. BPKAD No. 19, Bengkalis',
                'unit_id' => $units['BPKAD']->id ?? null,
                'position_id' => $positions['Kepala Seksi']->id ?? null,
                'position_desc' => 'Kepala Seksi Pelaporan',
                'rank_id' => $ranks['III/c']->id ?? null,
                'npwp' => '12.345.678.9-123.500',
                'bank_name' => 'Bank Riau Kepri',
                'bank_account_no' => '1234567834',
                'bank_account_name' => 'ARIEF YAHYA',
                'birth_date' => '2004-09-01',
                'gender' => 'L',
                'is_signer' => true,
            ],
            [
                'name' => 'Wishnutama',
                'email' => 'wishnutama@perjadin.test',
                'password' => Hash::make('password'),
                'nip' => '200510012010012001',
                'nik' => '1401010102050001',
                'gelar_depan' => '',
                'gelar_belakang' => 'S.E.',
                'phone' => '081234567835',
                'whatsapp' => '081234567835',
                'address' => 'Jl. BPKAD No. 20, Bengkalis',
                'unit_id' => $units['BPKAD']->id ?? null,
                'position_id' => $positions['Staff']->id ?? null,
                'position_desc' => 'Staff Pelaporan',
                'rank_id' => $ranks['III/b']->id ?? null,
                'npwp' => '12.345.678.9-123.501',
                'bank_name' => 'Bank Riau Kepri',
                'bank_account_no' => '1234567835',
                'bank_account_name' => 'WISHNUTAMA',
                'birth_date' => '2005-10-01',
                'gender' => 'L',
                'is_signer' => false,
            ],
        ];

        foreach ($employees as $employeeData) {
            User::create($employeeData);
        }

        $this->command->info('Employees seeded successfully!');
    }
}
