<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use App\Models\User;
use App\Models\Unit;
use App\Models\Position;
use App\Models\Rank;

class UsersSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Get reference data
        $units = Unit::all()->keyBy('code');
        $positions = Position::all()->keyBy('name');
        $ranks = Rank::all()->keyBy('code');

        $users = [
            [
                'name' => 'Administrator',
                'email' => 'admin@perjadin.test',
                'password' => Hash::make('password'),
                'nip' => '198501012010011001',
                'nik' => '1401010101850001',
                'gelar_depan' => '',
                'gelar_belakang' => 'S.Kom',
                'phone' => '081234567890',
                'whatsapp' => '081234567890',
                'address' => 'Jl. Raya Bengkalis No. 1, Bengkalis',
                'unit_id' => $units['SETDA']->id ?? null,
                'position_id' => $positions['Kepala Bagian Umum']->id ?? null,
                'position_desc' => 'Kepala Bagian Umum',
                'rank_id' => $ranks['III/d']->id ?? null,
                'npwp' => '12.345.678.9-123.456',
                'bank_name' => 'Bank Riau Kepri',
                'bank_account_no' => '1234567890',
                'bank_account_name' => 'ADMINISTRATOR',
                'birth_date' => '1985-01-01',
                'gender' => 'L',
                'is_signer' => true,
            ],
            [
                'name' => 'Sekretaris Daerah',
                'email' => 'sekda@perjadin.test',
                'password' => Hash::make('password'),
                'nip' => '197001011990031001',
                'nik' => '1401010101700001',
                'gelar_depan' => 'Dr.',
                'gelar_belakang' => 'S.E., M.M.',
                'phone' => '081234567891',
                'whatsapp' => '081234567891',
                'address' => 'Jl. Raya Bengkalis No. 2, Bengkalis',
                'unit_id' => $units['SETDA']->id ?? null,
                'position_id' => $positions['Sekretaris Daerah']->id ?? null,
                'position_desc' => 'Sekretaris Daerah',
                'rank_id' => $ranks['IV/e']->id ?? null,
                'npwp' => '12.345.678.9-123.457',
                'bank_name' => 'Bank Riau Kepri',
                'bank_account_no' => '1234567891',
                'bank_account_name' => 'SEKRETARIS DAERAH',
                'birth_date' => '1970-01-01',
                'gender' => 'L',
                'is_signer' => true,
            ],
            [
                'name' => 'Kepala Dinas Pendidikan',
                'email' => 'kadisdik@perjadin.test',
                'password' => Hash::make('password'),
                'nip' => '197505011995031001',
                'nik' => '1401010101750001',
                'gelar_depan' => '',
                'gelar_belakang' => 'S.Pd., M.Pd.',
                'phone' => '081234567892',
                'whatsapp' => '081234567892',
                'address' => 'Jl. Pendidikan No. 1, Bengkalis',
                'unit_id' => $units['DINDIK']->id ?? null,
                'position_id' => $positions['Kepala Dinas']->id ?? null,
                'position_desc' => 'Kepala Dinas Pendidikan',
                'rank_id' => $ranks['IV/b']->id ?? null,
                'npwp' => '12.345.678.9-123.458',
                'bank_name' => 'Bank Riau Kepri',
                'bank_account_no' => '1234567892',
                'bank_account_name' => 'KEPALA DINAS PENDIDIKAN',
                'birth_date' => '1975-05-01',
                'gender' => 'L',
                'is_signer' => true,
            ],
            [
                'name' => 'Kepala Dinas Kesehatan',
                'email' => 'kadiskes@perjadin.test',
                'password' => Hash::make('password'),
                'nip' => '197803011998032001',
                'nik' => '1401010101780001',
                'gelar_depan' => 'dr.',
                'gelar_belakang' => 'M.Kes.',
                'phone' => '081234567893',
                'whatsapp' => '081234567893',
                'address' => 'Jl. Kesehatan No. 1, Bengkalis',
                'unit_id' => $units['DINKES']->id ?? null,
                'position_id' => $positions['Kepala Dinas']->id ?? null,
                'position_desc' => 'Kepala Dinas Kesehatan',
                'rank_id' => $ranks['IV/b']->id ?? null,
                'npwp' => '12.345.678.9-123.459',
                'bank_name' => 'Bank Riau Kepri',
                'bank_account_no' => '1234567893',
                'bank_account_name' => 'KEPALA DINAS KESEHATAN',
                'birth_date' => '1978-03-01',
                'gender' => 'P',
                'is_signer' => true,
            ],
            [
                'name' => 'Kepala Dinas PUPR',
                'email' => 'kadispupr@perjadin.test',
                'password' => Hash::make('password'),
                'nip' => '198002011999031001',
                'nik' => '1401010101800001',
                'gelar_depan' => '',
                'gelar_belakang' => 'S.T., M.T.',
                'phone' => '081234567894',
                'whatsapp' => '081234567894',
                'address' => 'Jl. PUPR No. 1, Bengkalis',
                'unit_id' => $units['DINPUPR']->id ?? null,
                'position_id' => $positions['Kepala Dinas']->id ?? null,
                'position_desc' => 'Kepala Dinas PUPR',
                'rank_id' => $ranks['IV/b']->id ?? null,
                'npwp' => '12.345.678.9-123.460',
                'bank_name' => 'Bank Riau Kepri',
                'bank_account_no' => '1234567894',
                'bank_account_name' => 'KEPALA DINAS PUPR',
                'birth_date' => '1980-02-01',
                'gender' => 'L',
                'is_signer' => true,
            ],
            [
                'name' => 'Kepala Dinas Sosial',
                'email' => 'kadissos@perjadin.test',
                'password' => Hash::make('password'),
                'nip' => '198504011999032001',
                'nik' => '1401010101850002',
                'gelar_depan' => '',
                'gelar_belakang' => 'S.Sos., M.Si.',
                'phone' => '081234567895',
                'whatsapp' => '081234567895',
                'address' => 'Jl. Sosial No. 1, Bengkalis',
                'unit_id' => $units['DINSOS']->id ?? null,
                'position_id' => $positions['Kepala Dinas']->id ?? null,
                'position_desc' => 'Kepala Dinas Sosial',
                'rank_id' => $ranks['IV/b']->id ?? null,
                'npwp' => '12.345.678.9-123.461',
                'bank_name' => 'Bank Riau Kepri',
                'bank_account_no' => '1234567895',
                'bank_account_name' => 'KEPALA DINAS SOSIAL',
                'birth_date' => '1985-04-01',
                'gender' => 'P',
                'is_signer' => true,
            ],
            [
                'name' => 'Kepala Dinas Perhubungan',
                'email' => 'kadishub@perjadin.test',
                'password' => Hash::make('password'),
                'nip' => '198706011999031001',
                'nik' => '1401010101870001',
                'gelar_depan' => '',
                'gelar_belakang' => 'S.T., M.T.',
                'phone' => '081234567896',
                'whatsapp' => '081234567896',
                'address' => 'Jl. Perhubungan No. 1, Bengkalis',
                'unit_id' => $units['DINHUB']->id ?? null,
                'position_id' => $positions['Kepala Dinas']->id ?? null,
                'position_desc' => 'Kepala Dinas Perhubungan',
                'rank_id' => $ranks['IV/b']->id ?? null,
                'npwp' => '12.345.678.9-123.462',
                'bank_name' => 'Bank Riau Kepri',
                'bank_account_no' => '1234567896',
                'bank_account_name' => 'KEPALA DINAS PERHUBUNGAN',
                'birth_date' => '1987-06-01',
                'gender' => 'L',
                'is_signer' => true,
            ],
            [
                'name' => 'Kepala Dinas Lingkungan Hidup',
                'email' => 'kadislh@perjadin.test',
                'password' => Hash::make('password'),
                'nip' => '198809011999032001',
                'nik' => '1401010101880001',
                'gelar_depan' => '',
                'gelar_belakang' => 'S.T., M.Si.',
                'phone' => '081234567897',
                'whatsapp' => '081234567897',
                'address' => 'Jl. Lingkungan Hidup No. 1, Bengkalis',
                'unit_id' => $units['DINLH']->id ?? null,
                'position_id' => $positions['Kepala Dinas']->id ?? null,
                'position_desc' => 'Kepala Dinas Lingkungan Hidup',
                'rank_id' => $ranks['IV/b']->id ?? null,
                'npwp' => '12.345.678.9-123.463',
                'bank_name' => 'Bank Riau Kepri',
                'bank_account_no' => '1234567897',
                'bank_account_name' => 'KEPALA DINAS LINGKUNGAN HIDUP',
                'birth_date' => '1988-09-01',
                'gender' => 'P',
                'is_signer' => true,
            ],
            [
                'name' => 'Kepala Dinas Pariwisata',
                'email' => 'kadispar@perjadin.test',
                'password' => Hash::make('password'),
                'nip' => '199001012000031001',
                'nik' => '1401010101900001',
                'gelar_depan' => '',
                'gelar_belakang' => 'S.E., M.M.',
                'phone' => '081234567898',
                'whatsapp' => '081234567898',
                'address' => 'Jl. Pariwisata No. 1, Bengkalis',
                'unit_id' => $units['DINPAR']->id ?? null,
                'position_id' => $positions['Kepala Dinas']->id ?? null,
                'position_desc' => 'Kepala Dinas Pariwisata',
                'rank_id' => $ranks['IV/b']->id ?? null,
                'npwp' => '12.345.678.9-123.464',
                'bank_name' => 'Bank Riau Kepri',
                'bank_account_no' => '1234567898',
                'bank_account_name' => 'KEPALA DINAS PARIWISATA',
                'birth_date' => '1990-01-01',
                'gender' => 'L',
                'is_signer' => true,
            ],
            [
                'name' => 'Kepala Dinas Pertanian',
                'email' => 'kadispertanian@perjadin.test',
                'password' => Hash::make('password'),
                'nip' => '199102012000032001',
                'nik' => '1401010101910001',
                'gelar_depan' => '',
                'gelar_belakang' => 'S.P., M.Si.',
                'phone' => '081234567899',
                'whatsapp' => '081234567899',
                'address' => 'Jl. Pertanian No. 1, Bengkalis',
                'unit_id' => $units['DINPERTANIAN']->id ?? null,
                'position_id' => $positions['Kepala Dinas']->id ?? null,
                'position_desc' => 'Kepala Dinas Pertanian',
                'rank_id' => $ranks['IV/b']->id ?? null,
                'npwp' => '12.345.678.9-123.465',
                'bank_name' => 'Bank Riau Kepri',
                'bank_account_no' => '1234567899',
                'bank_account_name' => 'KEPALA DINAS PERTANIAN',
                'birth_date' => '1991-02-01',
                'gender' => 'P',
                'is_signer' => true,
            ],
            [
                'name' => 'Kepala Bagian Perencanaan',
                'email' => 'kabagren@perjadin.test',
                'password' => Hash::make('password'),
                'nip' => '198503012001031001',
                'nik' => '1401010101850003',
                'gelar_depan' => '',
                'gelar_belakang' => 'S.E., M.M.',
                'phone' => '081234567800',
                'whatsapp' => '081234567800',
                'address' => 'Jl. Raya Bengkalis No. 3, Bengkalis',
                'unit_id' => $units['SETDA']->id ?? null,
                'position_id' => $positions['Kepala Bagian Perencanaan']->id ?? null,
                'position_desc' => 'Kepala Bagian Perencanaan',
                'rank_id' => $ranks['III/d']->id ?? null,
                'npwp' => '12.345.678.9-123.466',
                'bank_name' => 'Bank Riau Kepri',
                'bank_account_no' => '1234567800',
                'bank_account_name' => 'KEPALA BAGIAN PERENCANAAN',
                'birth_date' => '1985-03-01',
                'gender' => 'L',
                'is_signer' => true,
            ],
            [
                'name' => 'Kepala Bagian Keuangan',
                'email' => 'kabagkeu@perjadin.test',
                'password' => Hash::make('password'),
                'nip' => '198604012001032001',
                'nik' => '1401010101860001',
                'gelar_depan' => '',
                'gelar_belakang' => 'S.E., M.Ak.',
                'phone' => '081234567801',
                'whatsapp' => '081234567801',
                'address' => 'Jl. Raya Bengkalis No. 4, Bengkalis',
                'unit_id' => $units['SETDA']->id ?? null,
                'position_id' => $positions['Kepala Bagian Keuangan']->id ?? null,
                'position_desc' => 'Kepala Bagian Keuangan',
                'rank_id' => $ranks['III/d']->id ?? null,
                'npwp' => '12.345.678.9-123.467',
                'bank_name' => 'Bank Riau Kepri',
                'bank_account_no' => '1234567801',
                'bank_account_name' => 'KEPALA BAGIAN KEUANGAN',
                'birth_date' => '1986-04-01',
                'gender' => 'P',
                'is_signer' => true,
            ],
            [
                'name' => 'Kepala Bagian Organisasi',
                'email' => 'kabagorg@perjadin.test',
                'password' => Hash::make('password'),
                'nip' => '198705012001031001',
                'nik' => '1401010101870002',
                'gelar_depan' => '',
                'gelar_belakang' => 'S.Sos., M.Si.',
                'phone' => '081234567802',
                'whatsapp' => '081234567802',
                'address' => 'Jl. Raya Bengkalis No. 5, Bengkalis',
                'unit_id' => $units['SETDA']->id ?? null,
                'position_id' => $positions['Kepala Bagian Organisasi']->id ?? null,
                'position_desc' => 'Kepala Bagian Organisasi',
                'rank_id' => $ranks['III/d']->id ?? null,
                'npwp' => '12.345.678.9-123.468',
                'bank_name' => 'Bank Riau Kepri',
                'bank_account_no' => '1234567802',
                'bank_account_name' => 'KEPALA BAGIAN ORGANISASI',
                'birth_date' => '1987-05-01',
                'gender' => 'L',
                'is_signer' => true,
            ],
            [
                'name' => 'Kepala Bagian Hukum',
                'email' => 'kabaghukum@perjadin.test',
                'password' => Hash::make('password'),
                'nip' => '198806012001032001',
                'nik' => '1401010101880002',
                'gelar_depan' => '',
                'gelar_belakang' => 'S.H., M.H.',
                'phone' => '081234567803',
                'whatsapp' => '081234567803',
                'address' => 'Jl. Raya Bengkalis No. 6, Bengkalis',
                'unit_id' => $units['SETDA']->id ?? null,
                'position_id' => $positions['Kepala Bagian Hukum']->id ?? null,
                'position_desc' => 'Kepala Bagian Hukum',
                'rank_id' => $ranks['III/d']->id ?? null,
                'npwp' => '12.345.678.9-123.469',
                'bank_name' => 'Bank Riau Kepri',
                'bank_account_no' => '1234567803',
                'bank_account_name' => 'KEPALA BAGIAN HUKUM',
                'birth_date' => '1988-06-01',
                'gender' => 'P',
                'is_signer' => true,
            ],
            [
                'name' => 'Kepala Bagian Pemerintahan',
                'email' => 'kabagpem@perjadin.test',
                'password' => Hash::make('password'),
                'nip' => '198907012001031001',
                'nik' => '1401010101890001',
                'gelar_depan' => '',
                'gelar_belakang' => 'S.Sos., M.Si.',
                'phone' => '081234567804',
                'whatsapp' => '081234567804',
                'address' => 'Jl. Raya Bengkalis No. 7, Bengkalis',
                'unit_id' => $units['SETDA']->id ?? null,
                'position_id' => $positions['Kepala Bagian Pemerintahan']->id ?? null,
                'position_desc' => 'Kepala Bagian Pemerintahan',
                'rank_id' => $ranks['III/d']->id ?? null,
                'npwp' => '12.345.678.9-123.470',
                'bank_name' => 'Bank Riau Kepri',
                'bank_account_no' => '1234567804',
                'bank_account_name' => 'KEPALA BAGIAN PEMERINTAHAN',
                'birth_date' => '1989-07-01',
                'gender' => 'L',
                'is_signer' => true,
            ],
            [
                'name' => 'Kepala Bagian Kesejahteraan Rakyat',
                'email' => 'kabagkesra@perjadin.test',
                'password' => Hash::make('password'),
                'nip' => '199008012001032001',
                'nik' => '1401010101900002',
                'gelar_depan' => '',
                'gelar_belakang' => 'S.Sos., M.Si.',
                'phone' => '081234567805',
                'whatsapp' => '081234567805',
                'address' => 'Jl. Raya Bengkalis No. 8, Bengkalis',
                'unit_id' => $units['SETDA']->id ?? null,
                'position_id' => $positions['Kepala Bagian Kesejahteraan Rakyat']->id ?? null,
                'position_desc' => 'Kepala Bagian Kesejahteraan Rakyat',
                'rank_id' => $ranks['III/d']->id ?? null,
                'npwp' => '12.345.678.9-123.471',
                'bank_name' => 'Bank Riau Kepri',
                'bank_account_no' => '1234567805',
                'bank_account_name' => 'KEPALA BAGIAN KESEJAHTERAAN RAKYAT',
                'birth_date' => '1990-08-01',
                'gender' => 'P',
                'is_signer' => true,
            ],
            [
                'name' => 'Kepala Bagian Ekonomi',
                'email' => 'kabageko@perjadin.test',
                'password' => Hash::make('password'),
                'nip' => '199109012001031001',
                'nik' => '1401010101910002',
                'gelar_depan' => '',
                'gelar_belakang' => 'S.E., M.M.',
                'phone' => '081234567806',
                'whatsapp' => '081234567806',
                'address' => 'Jl. Raya Bengkalis No. 9, Bengkalis',
                'unit_id' => $units['SETDA']->id ?? null,
                'position_id' => $positions['Kepala Bagian Ekonomi']->id ?? null,
                'position_desc' => 'Kepala Bagian Ekonomi',
                'rank_id' => $ranks['III/d']->id ?? null,
                'npwp' => '12.345.678.9-123.472',
                'bank_name' => 'Bank Riau Kepri',
                'bank_account_no' => '1234567806',
                'bank_account_name' => 'KEPALA BAGIAN EKONOMI',
                'birth_date' => '1991-09-01',
                'gender' => 'L',
                'is_signer' => true,
            ],
            [
                'name' => 'Kepala Bagian Infrastruktur',
                'email' => 'kabaginfra@perjadin.test',
                'password' => Hash::make('password'),
                'nip' => '199210012001032001',
                'nik' => '1401010101920001',
                'gelar_depan' => '',
                'gelar_belakang' => 'S.T., M.T.',
                'phone' => '081234567807',
                'whatsapp' => '081234567807',
                'address' => 'Jl. Raya Bengkalis No. 10, Bengkalis',
                'unit_id' => $units['SETDA']->id ?? null,
                'position_id' => $positions['Kepala Bagian Infrastruktur']->id ?? null,
                'position_desc' => 'Kepala Bagian Infrastruktur',
                'rank_id' => $ranks['III/d']->id ?? null,
                'npwp' => '12.345.678.9-123.473',
                'bank_name' => 'Bank Riau Kepri',
                'bank_account_no' => '1234567807',
                'bank_account_name' => 'KEPALA BAGIAN INFRASTRUKTUR',
                'birth_date' => '1992-10-01',
                'gender' => 'P',
                'is_signer' => true,
            ],
            [
                'name' => 'Kepala Bagian Administrasi Pembangunan',
                'email' => 'kabagadbang@perjadin.test',
                'password' => Hash::make('password'),
                'nip' => '199311012001031001',
                'nik' => '1401010101930001',
                'gelar_depan' => '',
                'gelar_belakang' => 'S.Sos., M.Si.',
                'phone' => '081234567808',
                'whatsapp' => '081234567808',
                'address' => 'Jl. Raya Bengkalis No. 11, Bengkalis',
                'unit_id' => $units['SETDA']->id ?? null,
                'position_id' => $positions['Kepala Bagian Administrasi Pembangunan']->id ?? null,
                'position_desc' => 'Kepala Bagian Administrasi Pembangunan',
                'rank_id' => $ranks['III/d']->id ?? null,
                'npwp' => '12.345.678.9-123.474',
                'bank_name' => 'Bank Riau Kepri',
                'bank_account_no' => '1234567808',
                'bank_account_name' => 'KEPALA BAGIAN ADMINISTRASI PEMBANGUNAN',
                'birth_date' => '1993-11-01',
                'gender' => 'L',
                'is_signer' => true,
            ],
            [
                'name' => 'Kepala Bagian Protokol dan Komunikasi Pimpinan',
                'email' => 'kabagprotokol@perjadin.test',
                'password' => Hash::make('password'),
                'nip' => '199412012001032001',
                'nik' => '1401010101940001',
                'gelar_depan' => '',
                'gelar_belakang' => 'S.Sos., M.I.Kom.',
                'phone' => '081234567809',
                'whatsapp' => '081234567809',
                'address' => 'Jl. Raya Bengkalis No. 12, Bengkalis',
                'unit_id' => $units['SETDA']->id ?? null,
                'position_id' => $positions['Kepala Bagian Protokol dan Komunikasi Pimpinan']->id ?? null,
                'position_desc' => 'Kepala Bagian Protokol dan Komunikasi Pimpinan',
                'rank_id' => $ranks['III/d']->id ?? null,
                'npwp' => '12.345.678.9-123.475',
                'bank_name' => 'Bank Riau Kepri',
                'bank_account_no' => '1234567809',
                'bank_account_name' => 'KEPALA BAGIAN PROTOKOL DAN KOMUNIKASI PIMPINAN',
                'birth_date' => '1994-12-01',
                'gender' => 'P',
                'is_signer' => true,
            ],
            [
                'name' => 'Kepala Bagian Pengadaan Barang dan Jasa',
                'email' => 'kabagpengadaan@perjadin.test',
                'password' => Hash::make('password'),
                'nip' => '199501012001031001',
                'nik' => '1401010101950001',
                'gelar_depan' => '',
                'gelar_belakang' => 'S.E., M.M.',
                'phone' => '081234567810',
                'whatsapp' => '081234567810',
                'address' => 'Jl. Raya Bengkalis No. 13, Bengkalis',
                'unit_id' => $units['SETDA']->id ?? null,
                'position_id' => $positions['Kepala Bagian Pengadaan Barang dan Jasa']->id ?? null,
                'position_desc' => 'Kepala Bagian Pengadaan Barang dan Jasa',
                'rank_id' => $ranks['III/d']->id ?? null,
                'npwp' => '12.345.678.9-123.476',
                'bank_name' => 'Bank Riau Kepri',
                'bank_account_no' => '1234567810',
                'bank_account_name' => 'KEPALA BAGIAN PENGADAAN BARANG DAN JASA',
                'birth_date' => '1995-01-01',
                'gender' => 'L',
                'is_signer' => true,
            ],
            [
                'name' => 'Kepala Bagian Pengawasan',
                'email' => 'kabagwas@perjadin.test',
                'password' => Hash::make('password'),
                'nip' => '199602012001032001',
                'nik' => '1401010101960001',
                'gelar_depan' => '',
                'gelar_belakang' => 'S.E., M.M.',
                'phone' => '081234567811',
                'whatsapp' => '081234567811',
                'address' => 'Jl. Raya Bengkalis No. 14, Bengkalis',
                'unit_id' => $units['SETDA']->id ?? null,
                'position_id' => $positions['Kepala Bagian Pengawasan']->id ?? null,
                'position_desc' => 'Kepala Bagian Pengawasan',
                'rank_id' => $ranks['III/d']->id ?? null,
                'npwp' => '12.345.678.9-123.477',
                'bank_name' => 'Bank Riau Kepri',
                'bank_account_no' => '1234567811',
                'bank_account_name' => 'KEPALA BAGIAN PENGAWASAN',
                'birth_date' => '1996-02-01',
                'gender' => 'P',
                'is_signer' => true,
            ],
            [
                'name' => 'Kepala Bagian Kerjasama',
                'email' => 'kabagkerjasama@perjadin.test',
                'password' => Hash::make('password'),
                'nip' => '199703012001031001',
                'nik' => '1401010101970001',
                'gelar_depan' => '',
                'gelar_belakang' => 'S.Sos., M.Si.',
                'phone' => '081234567812',
                'whatsapp' => '081234567812',
                'address' => 'Jl. Raya Bengkalis No. 15, Bengkalis',
                'unit_id' => $units['SETDA']->id ?? null,
                'position_id' => $positions['Kepala Bagian Kerjasama']->id ?? null,
                'position_desc' => 'Kepala Bagian Kerjasama',
                'rank_id' => $ranks['III/d']->id ?? null,
                'npwp' => '12.345.678.9-123.478',
                'bank_name' => 'Bank Riau Kepri',
                'bank_account_no' => '1234567812',
                'bank_account_name' => 'KEPALA BAGIAN KERJASAMA',
                'birth_date' => '1997-03-01',
                'gender' => 'L',
                'is_signer' => true,
            ],
            [
                'name' => 'Kepala Bagian Kesejahteraan Sosial',
                'email' => 'kabagkesos@perjadin.test',
                'password' => Hash::make('password'),
                'nip' => '199804012001032001',
                'nik' => '1401010101980001',
                'gelar_depan' => '',
                'gelar_belakang' => 'S.Sos., M.Si.',
                'phone' => '081234567813',
                'whatsapp' => '081234567813',
                'address' => 'Jl. Raya Bengkalis No. 16, Bengkalis',
                'unit_id' => $units['SETDA']->id ?? null,
                'position_id' => $positions['Kepala Bagian Kesejahteraan Sosial']->id ?? null,
                'position_desc' => 'Kepala Bagian Kesejahteraan Sosial',
                'rank_id' => $ranks['III/d']->id ?? null,
                'npwp' => '12.345.678.9-123.479',
                'bank_name' => 'Bank Riau Kepri',
                'bank_account_no' => '1234567813',
                'bank_account_name' => 'KEPALA BAGIAN KESEJAHTERAAN SOSIAL',
                'birth_date' => '1998-04-01',
                'gender' => 'P',
                'is_signer' => true,
            ],
            [
                'name' => 'Kepala Bagian Pemberdayaan Masyarakat',
                'email' => 'kabagpemberdayaan@perjadin.test',
                'password' => Hash::make('password'),
                'nip' => '199905012001031001',
                'nik' => '1401010101990001',
                'gelar_depan' => '',
                'gelar_belakang' => 'S.Sos., M.Si.',
                'phone' => '081234567814',
                'whatsapp' => '081234567814',
                'address' => 'Jl. Raya Bengkalis No. 17, Bengkalis',
                'unit_id' => $units['SETDA']->id ?? null,
                'position_id' => $positions['Kepala Bagian Pemberdayaan Masyarakat']->id ?? null,
                'position_desc' => 'Kepala Bagian Pemberdayaan Masyarakat',
                'rank_id' => $ranks['III/d']->id ?? null,
                'npwp' => '12.345.678.9-123.480',
                'bank_name' => 'Bank Riau Kepri',
                'bank_account_no' => '1234567814',
                'bank_account_name' => 'KEPALA BAGIAN PEMBERDAYAAN MASYARAKAT',
                'birth_date' => '1999-05-01',
                'gender' => 'L',
                'is_signer' => true,
            ],
            [
                'name' => 'Kepala Bagian Pemberdayaan Perempuan dan Perlindungan Anak',
                'email' => 'kabagp3a@perjadin.test',
                'password' => Hash::make('password'),
                'nip' => '200006012001032001',
                'nik' => '1401010102000001',
                'gelar_depan' => '',
                'gelar_belakang' => 'S.Sos., M.Si.',
                'phone' => '081234567815',
                'whatsapp' => '081234567815',
                'address' => 'Jl. Raya Bengkalis No. 18, Bengkalis',
                'unit_id' => $units['SETDA']->id ?? null,
                'position_id' => $positions['Kepala Bagian Pemberdayaan Perempuan dan Perlindungan Anak']->id ?? null,
                'position_desc' => 'Kepala Bagian Pemberdayaan Perempuan dan Perlindungan Anak',
                'rank_id' => $ranks['III/d']->id ?? null,
                'npwp' => '12.345.678.9-123.481',
                'bank_name' => 'Bank Riau Kepri',
                'bank_account_no' => '1234567815',
                'bank_account_name' => 'KEPALA BAGIAN PEMBERDAYAAN PEREMPUAN DAN PERLINDUNGAN ANAK',
                'birth_date' => '2000-06-01',
                'gender' => 'P',
                'is_signer' => true,
            ],
        ];

        foreach ($users as $userData) {
            User::create($userData);
        }

        $this->command->info('Users seeded successfully!');
    }
}
